version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend
