sonar.projectKey=Ecommerce-Project
sonar.projectName=Ecommerce Project
sonar.host.url=http://localhost:9000

sonar.sources=backend/src,frontend/src
sonar.exclusions=node_modules/**,frontend/node_modules/**,backend/node_modules/**

sonar.sourceEncoding=UTF-8
