apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: roronoazoro1350/backend:latest
          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: MONGO_URI
              value: "mongodb+srv://devops-user:AllMighty123@devops.lrsjkfn.mongodb.net/ecommerce?retryWrites=true&w=majority"
